:concurrency: 5
:queues:
  - default
  - mailers

:scheduler:
  :enabled: true
  :schedule:
    ebay_fetch_orders_job:
      cron: '0 * * * *' # 毎時0分に実行
      class: EbayFetchOrdersJob
      queue: default
